name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create Data directory
      run: |
        mkdir -p Data
        echo "This directory is for Excel files" > Data/README.txt
    
    - name: Build executable
      run: |
        pyinstaller importxl.spec
    
    - name: Copy additional files and directories
      run: |
        echo "Copying additional files to dist\LAB14_Excel_Importer\"
        copy run_importer.bat dist\LAB14_Excel_Importer\
        copy README_Windows.md dist\LAB14_Excel_Importer\
        copy requirements.txt dist\LAB14_Excel_Importer\
        echo "Copying directories..."
        xcopy static dist\LAB14_Excel_Importer\static /E /I /Y
        xcopy config dist\LAB14_Excel_Importer\config /E /I /Y
        xcopy Data dist\LAB14_Excel_Importer\Data /E /I /Y
        echo "Files and directories copied successfully"
    
    - name: Debug - List dist contents
      run: |
        echo "Contents of dist folder:"
        dir dist
        echo "Contents of LAB14_Excel_Importer folder:"
        dir dist\LAB14_Excel_Importer
        echo "Checking if executable exists:"
        if exist "dist\LAB14_Excel_Importer\LAB14_Excel_Importer.exe" (
            echo "EXECUTABLE FOUND!"
        ) else (
            echo "EXECUTABLE NOT FOUND!"
        )
    
    - name: Create distribution package
      run: |
        cd dist
        powershell Compress-Archive -Path "LAB14_Excel_Importer" -DestinationPath "LAB14_Excel_Importer_Windows.zip"
    
    - name: Debug - List zip contents
      run: |
        cd dist
        powershell "Expand-Archive -Path 'LAB14_Excel_Importer_Windows.zip' -DestinationPath 'temp_extract' -Force"
        echo "Contents of extracted zip:"
        dir temp_extract
        echo "Contents of LAB14_Excel_Importer in zip:"
        dir temp_extract\LAB14_Excel_Importer
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: LAB14_Excel_Importer_Windows
        path: dist/LAB14_Excel_Importer_Windows.zip 