name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create Data directory
      run: |
        mkdir -p Data
        echo "This directory is for Excel files" > Data/README.txt
    
    - name: Build executable
      run: |
        pyinstaller importxl.spec
    
    - name: Copy additional files
      run: |
        copy run_importer.bat dist\LAB14_Excel_Importer\
        copy README_Windows.md dist\LAB14_Excel_Importer\
        copy requirements.txt dist\LAB14_Excel_Importer\
    
    - name: Create distribution package
      run: |
        cd dist
        powershell Compress-Archive -Path "LAB14_Excel_Importer" -DestinationPath "LAB14_Excel_Importer_Windows.zip"
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: LAB14_Excel_Importer_Windows
        path: dist/LAB14_Excel_Importer_Windows.zip 